import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import CenteredContainer from "../components/common/CenteredContainer";
import Dialog from "../components/common/Dialog";
import UrlShortener from "../components/UrlShortener";

const Home: NextPage = () => {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CenteredContainer>
        <UrlShortener />

        {session && <Dialog text="You are logged in" variant="info" />}
      </CenteredContainer>
    </>
  );
};

export default Home;
